export const GET_POKEMONS = "GET_POKEMONS";
export const GET_POKE_BY_ID = "GET_POKE_BY_ID"; 
export const GET_POKE_BY_NAME = "GET_POKE_BY_NAME";
export const GET_POKE_DETAILS = "GET_POKE_DETAILS";
export const CLEAN_POKE_DETAILS = "CLEAN_POKE_DETAILS"; 
export const FILTER_POKEMONS = "FILTER_POKEMONS"; 